### ISSUE TITLE
Peer to peer code review week 5

### ISSUE THREAD

**Issue by sumon766** [Tshobohwa/Technology-Innovation-Summit-2023#1]
Hello Salomon, you are doing a great job and your progress on this project is really awesome. I have some minor fixes to suggest to you. Firstly, I suggest you put the script files at the end of your code just before the end of the body tag. It will help the page load faster and avoid any possible errors. Also, there is one more thing I noticed in your code is that you have missed using semicolons many times in your script file, use semicolons at the end of every line in your programming code or there will always be a possibility of throwing unknown errors.

**Comment by supreeti** [comment]
Great Job so far. Color code and mobile section nicely made. But I suggest to use capital letter while starting paragraph and use some content on about page. Please fix your navigation bar with a background with a fix height.
